### PR TITLE
Switch to sapmachine-11-jdk

### PR DESCRIPTION
**Pull request by Regloom**
Replace sapmachine-11-jre package with sapmachine-11-jdk (no longer provided). 
see #32 and https://github.com/SAP/SapMachine/issues/910

### CODE REVIEW

**Comment by marcosvega91** [comment]
Hi @mikezaschka and @Regloom thanks for the fix. Do you know when a new version will be available? Thanks

**Comment by valpankaj** [comment]
Hi Experts,

during npx mbt build command, mtar is generated with gen folder having apt.yml,  deploy.sh and many others files. Both apt.yml and deploy.sh is having sapmachine-11.jre default config. 

how can we change the default config to sapmachine-11.jdk to run our app on SCP?

**Comment by epalmen** [comment]
Hey any idea when the fix wil be available? Or is there a workaround, kind of stuck at the moment.

**Comment by gregorwolf** [comment]
Please check out https://github.com/gregorwolf/pg-beershop/commit/5272c706fc7b7a6413bb94da4d8e412f12e246e2 how I fixed the jre issue by using jdk. Hope that helps.

**Pull request merged**
